services:

  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: mahesh050917/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: mahesh050917/user:1.0.0
    container_name: user
    depends_on:
      - redis
      - mongodb

  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    image: mahesh050917/cart:1.0.0
    container_name: cart

  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: mahesh050917/mongodb:1.0.0
    container_name: mongodb

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: mahesh050917/redis:1.0.0
    container_name: redis

networks:
  default:
    driver: bridge
    name: roboshop