services:

  catalogue:
    build: 
     dockerfile: catalogue.Dockerfile
    image: mahesh050917/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: 
      dockerfile: user.Dockerfile
    image: mahesh050917/user:1.0.0
    container_name: user
    depends_on:
      - redis
      - mongodb
  cart:
     build: 
      dockerfile: cart.Dockerfile
     image: mahesh050917/cart:1.0.0
     container_name: cart
  mongodb:
    build: 
      dockerfile: mongodb.Dockerfile           # it moves to mongodb directory
    image: mahesh050917/mongodb:1.0.0          # docker build -t mahesh050917/monogdb:1.0.0 
    container_name: mongodb
  redis:
    build: 
     dockerfile: redis.Dockerfile
    image: mahesh050917/redis:1.0.0
    container_name: redis
networks:
  default: 
    driver: bridge
    name: roboshop
    external: false                           #if true you need to create network manually.
